# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('post_image', models.ImageField(blank=True, upload_to=social.models.post_upload_location)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile_number', models.PositiveIntegerField()),
                ('is_mobile_visible', models.BooleanField(default=False)),
                ('is_email_visible', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to=social.models.upload_location)),
                ('friend_requests_received', models.ManyToManyField(blank=True, related_name='_profile_friend_requests_received_+', to='social.Profile')),
                ('friend_requests_sent', models.ManyToManyField(blank=True, related_name='_profile_friend_requests_sent_+', to='social.Profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='social.Profile')),
            ],
            options={
                'verbose_name_plural': 'UserProfiles',
                'verbose_name': ('UserProfile',),
                'db_table': ('user_profile',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
