# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
