# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20171002_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='initial-slug', unique=True),
            preserve_default=False,
        ),
    ]
