# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-25 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20171106_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend_requests_received',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friend_requests_sent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
